version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: vue-next
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  target-branch: vue-next
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
