packages:
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - esbuild

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  node-forge@<1.3.2: '>=1.3.2'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
